apiVersion: apps/v1
kind: Deployment
metadata:
  name: todofrontendapp
  namespace: todoapp
  labels:
    app: todofrontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: todofrontend
  template:
    metadata:
      labels:
        app: todofrontend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
