apiVersion: v1
kind: Service
metadata:
  name: todofrontendapp
  namespace: todoapp # namespace belirtildi
  labels:
    app: todofrontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: todofrontend
---
